version: "3.9"

services:
  api:
    build: .
    container_name: springboot-api
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/${MYSQL_DATABASE}
      - SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      - SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
  db:
    image: mysql
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      -"3306:3306"
    volumes:
      -db_data:/var/lib/mysql
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network: